### ISSUE TITLE
Please add a distinct version number for -dev builds to plugin.yml

### ISSUE THREAD

**Issue by totemo** [SBPrime/AsyncWorldEdit#123]
I'm here representing one of your customers, @NerdNu.  We use scripts to manage plugin symlinks.  The scripts consult plugin.yml in the plugin JAR file to determine a plugin's version number.

You currently assign the same version number to -dev and non-dev builds of AsyncWorldEdit.

Please *distinctly* identify different code.  It would be sufficient to add a monotonically incrementing build number to all binary products.  Including "dev" or "snapshot" in the dev builds would also be helpful.

I suspect similar remarks apply to the generated AsyncWorldEditInjector JAR file.

**Comment by SBPrime** [comment]
I think that you don't know why there is a DEV version and a regular version of AWE. The DEV version is not a different version of AWE feature wise. It does not have any additional features or untested code. The only difference with those 2 versions is that the DEV version is for WorldEdit dev builds and the other one is for WorldEdit found on DevBukkit. I don't want to go into technical details what exactly is different in those 2 versions. Bottom line is that there is no difference for the end user. If you are using the dev builds of WE you need the dev version of AWE. If you are using WE from DevBukkit use the regular version of AWE.

I decided to not add a different version for AWE adn AWE-Dev because I did not want ppl to get confused. I always name the dev version "AsyncWorldEdit-dev.jar" and the regular "AsyncWorldEdit.jar". While you download the plugin from SpigotMc you should handle those 2 versions as 2 different plugins.

**Comment by SBPrime** [comment]
I did not notice that you put this on the free version of the plugin. If you want to continue the discussion please open a ticket in the premium version issues or contact me on spigot.
