### ISSUE TITLE
Convert plugin to Maven or Gradle

### ISSUE THREAD

**Issue by DoNotSpamPls** [SBPrime/AsyncWorldEdit#150]
you know why that's a good thing

**Comment by SBPrime** [comment]
I decided not to go with maven simply because how the plugin is built. It needs to depend on multiple versions of the same artifact, some dependencies are not available on maven and most important it depends on spigot/craftbukkit not bukkit. Never the less I'll consider this for the future since I was thinking of doing something similar (gradle).

**Comment by SBPrime** [comment]
Maven migration is planed for future but it has a low priority.

**Comment by SBPrime** [comment]
The current master was migrated to maven.
