### ISSUE TITLE
No .jar download only sourcecode

### ISSUE THREAD

**Issue by ThorinEk** [SBPrime/AsyncWorldEdit#157]
Hello. 
When I try to download the AWE plugin there is just nothing to be found, Only txt file and sourcecode stuff, i tried downloading all but non contain the actual .jar file that i need. 
Is this the same for everyone or just me?
![nodownload](https://user-images.githubusercontent.com/36575668/36345613-ac0dcb12-142e-11e8-8b07-f6b09d0ff3ae.JPG)

**Comment by SBPrime** [comment]
Since the premium code was added to the github the jar is only available to download from spigot for premium users. The free version is available only as source code for everyone to compile by themselves.

The jar is available only for the older versions.

The free version link: https://www.spigotmc.org/resources/asyncworldedit.327/
The premium version link: https://www.spigotmc.org/resources/asyncworldedit-premium.9661/

Quote from the premium page:

>The premium version
>Starting from the 1'st of January 2018 the AsyncWorldEdit Premium and the free versions are again one software. All the changes and features added to the premium are now available for everyone.
>
>Ok so wher's the cache? The free version will be released only as source code for everyone to compile by themselves. There will be no jar releases for the free version. In addition I will provide support only for users that bought the premium version.
>
>So what do I get when I buy the premium version? First thin, and most important, you will get support (starting from simple trouble shooting to help in working with the source code). Secondly you won't need to build the jar file by yourself, you will get a pre-build jar file. WARNING: You can download a jar file of the plugin only from the Premium download page, if you got it from other source it is an illegal copy (providing downloads for the jar breaks the license).
