### ISSUE TITLE
Bug with entities transformation during commands //paste and //stack

### ISSUE THREAD

**Issue by Qveshn** [SBPrime/AsyncWorldEdit#166]
AWE 3.5.2
WE 6.1.9 (Build #3736) http://builds.enginehub.org/job/worldedit/last-successful?branch=master

Symptoms:
1, select region with entities (Armo Stands, frames, mobs)
run command //stack 3 up
You will see that entities are shifted more than once
2.  select region with entities (Armo Stands, frames, mobs)
run commands: //copy -e //rotate 90 //paste
You will see that entities are rotated by 180 degrees

**This bug also in WorldEdit**
I know that you are not owner of that project.
I have fixed it and tested in my fork of WE.
Also, I have made PR to WE. Look it here: https://github.com/sk89q/WorldEdit/pull/416
You can find out there what was wrong

**Comment by SBPrime** [comment]
Currently I'm working on removing the injector from the code. This will solve lot of compatibility issues. The error that you described is not AWE specific (its in the WE code), because of that I'm not planing to change anything in the AWE code. It must be fixed in WE code. When the new version of injector is ready everything will work out of the box.

WONT FIX.
