### ISSUE TITLE
BPS keeps dropping and won't hold over 3k

### ISSUE THREAD

**Issue by Bin0ry** [SBPrime/AsyncWorldEdit#281]
Not sure what's going on here...but it seems like this plugin has some serious potential but lacking the configuration description to setup correctly. I have mine running on a pretty good machine i7 8700-k 32gb of DDR4 memory, and 1070TI, yet...I'm stilling having issues with the programs "BPS" I've set up so that the program can max out...and try to place as many blocks as it can per second...yet it will just have second of "10k plus! BPS" and then just drop off to "0.8 BPS" what's going on here? My server isn't showing heavy load at 10k plus BPS yet it will sometimes even crash and the time left will go crazy high until it recovery and keep steady around 3k BPS.  I've attached the Config file. This Schematic is 40 million blocks...but it should be able to handle this. 
[Config.txt](https://github.com/SBPrime/AsyncWorldEdit/files/4020032/Config.txt)

**Comment by SBPrime** [comment]
The 3.6.17 will aim on speed optimization (more or less it should speed up all operations ~2.5x).
The BPS is (most likely) low because of block get. You should check the server log for any errors, and see if you are not using any plugins that can cause speed to drop. I would suggest that you change the force flush to ~10k.

**Comment by Bin0ry** [comment]
I will be able to test it soon. Alittle busy atm. I will let you know as soon as I can

**Comment by Bin0ry** [comment]
Also, no console logs arose when this came about. I will get back to you asap
