### ISSUE TITLE
Wrie full API

### ISSUE THREAD

**Issue by SBPrime** [SBPrime/AsyncWorldEdit#29]

**Comment by Intensearmadillo** [comment]
I agree, there needs to be some way for developers to know when a job is finished, how long until it will be finished, and the current BPS... the same information the player is able to contain when using worldedit.

**Comment by SBPrime** [comment]
@Intensearmadillo: As you can see all the features that you have mentioned are available.

To get BlockPlacer:

    aweMain =AsyncWorldEditMain.getInstance()
    bPlacer = aweMain.getBlockPlacer();

For job start/finish use:
    
    bPlacer.addListener(myListener);

Then for job state change (in job added listener):

   job.addStateChangedListener(myJobStateListener);

For block placing speed use:

  playerEntry = blockPlacer.getPlayerEvents(player);
  playerEntry.getSpeed(); <--- current block placing speed
  playerEntry.getQueue(); <--- current blocks queue = how many blocks there are to place, use to calculate the time.

**Comment by MylesIsCool** [comment]
@SBPrime 
Hey thanks for the information above, I have a job being created entirely from code. 
```
"EditSession es = new AsyncEditSessionFactory(AsyncWorldEditMain.getInstance(), we.getWorldEdit().getEventBus()).getEditSession(new BukkitWorld(world), 99999999);"
```
Which then uses it to paste, the issue I have is the player I use later on...

```
CuboidClipboard cc = new AsyncCuboidClipboard(PlayerEntry.UNKNOWN, CuboidClipboard.loadSchematic(f));
```

Is an anonymous player, and multiple of these may be setting off at once, meaning that I can't just use the player unknown name or what. Is there a way to turn an EditSession into the a Job ID so I can keep track of these?

I don't really want to make fake players as that's not very good practice, is there anything you would suggest for this sort of thing?

I'd also like to not rely on timing it to catch the job in the listener because it's possible that the jobs could have multiple added at a time and i'd never be able to work out which one belongs to which part of it.

I can't see any way to turn a job into more information such as block coordinates etc?

**Comment by SBPrime** [comment]
@MylesIsCool First of all don't use **new AsyncEditSession**. Use getEditSessionFactory from WorldEdit. Regarding "Fake player" in AWE its simply a UUID, so its not a bad practice :) 

You could use:
* BlockPlacer.PerformAsAsyncJob(...)
* AsyncEditSessionFactory.getThreadSafeEditSession(...) <--- Caste the EditSession factory from WorldEdit.getEditSessionFactory, don't use the getEditSession!
* new AsyncCuboidClipboard(...) <--- that's what you used

Whan you use this, remember to add the jobAdded listener, and jobStateChanged listener.

**Comment by Intensearmadillo** [comment]
Any way to get composition of certain blocks in a region asynchronously and return its percentage? It would be extremely useful for calculating the percentages of mines. Thanks.

**Comment by SBPrime** [comment]
try using the standard WE function (getDistribution if i remember correctly) within PerformAsAsyncJob.

**Comment by SBPrime** [comment]
Implemented premium API. Details available here:
https://github.com/SBPrime/AsyncWorldEdit-api
