### ISSUE TITLE
Regen short lag spike

### ISSUE THREAD

**Issue by x1p** [SBPrime/AsyncWorldEdit#316]
Whenever I do `//regen` (per chunk), a short lag spike occurs of about 3 seconds. Mobs freeze, players notice it clearly. After that, normal (re)placing of blocks process. The placing of the blocks itself is smooth as butter. But I wonder if there is anything I can do to minimize the initial spike. I suspect it has something to do with WE itself.

AWE premium 3.7.2
Config: https://pastebin.com/v5uGjGiM
WE 7.1.0
WG 7.0.2

**Comment by SBPrime** [comment]
Did you use cuboid selection?
I got reports that non cuboid selections have some issues.

Assuming everything works: regen will always result in small amount of TPS drop. There is nothing that I can do about it (I can slow it down so the average TPS drops less). This is caused by the fact tha regen is an atomic operation that can't be divided further, in addition it needs to be executed on the main thread.
