### ISSUE TITLE
False update info

### ISSUE THREAD

**Issue by ZandercraftGames** [SBPrime/AsyncWorldEdit#319]
The non-premium plugin states that there is a new version `3.7.2` and has done such for quite some time now, but only `3.6.20` is available. This is extremely annoying and has been happening for almost a month now with the version number getting further away from `3.6.20`.

**Comment by ZandercraftGames** [comment]
If this is informing about the premium version as a nuisance, it never did in the past and that is quite annoying and not like the AsyncWE team to do. To be honest, it is kind-of trashy to try to get people to buy it by using the premium update branch as the update-notifier simply to annoy the heck out of admins/server owners. If you want people to buy the premium, just make it worth their while. Don't make the free version give a negative impression to those who use it as being broken, as that is not the way to go when you want people to buy your premium plugin to support you. It just makes people mad.

**Comment by SBPrime** [comment]
This was like this for 1-2 years now, since codebase merger of premium, non-premium. I don't know how you missed that.  As I said multiple times: premium and free uses the same codebase. It was never intended to advertise the premium version. For me its more important to inform about premium updates then free thats why you get the information. At this moment if it annoys you, simply disable the checks.
