### ISSUE TITLE
not stable blocks per second since 1.16.1

### ISSUE THREAD

**Issue by MarcusCoding** [SBPrime/AsyncWorldEdit#332]
Hello there,

we're using AsyncWorldEdit on our server to copy / paste big structures (30 million blocks and more ) through our world.

But since the version 3.7.5, the blockspeed  dropped and is not stable.

While pasting a selection of 32 million blocks it switches between 30 and 9000 bps.

Last night we moved 45 million blocks and it took 6 hours to paste it.

Our current config:

[config.txt](https://github.com/SBPrime/AsyncWorldEdit/files/4908921/config.txt)

current server configuration:

I7 3930 K @ 3.20 GHz
6 C / 12 T

32 GB RAM

Thanks for the help.

**Comment by SBPrime** [comment]
Please enable debug mode, do 1 block edit and send me the log. The block placing speed is low. On my test machine I get ~200k.

**Comment by MarcusCoding** [comment]
Thanks for the quick response.

Here is the log for //set 1.

[debugLogAWE.txt](https://github.com/SBPrime/AsyncWorldEdit/files/4909231/debugLogAWE.txt)

**Comment by SBPrime** [comment]
After looking into the problem there is nothing obvious. What is the free ram on your server after doing the copy?

**Comment by MarcusCoding** [comment]
I haven't looked at the ram after the copy. But I can do another run and post the free ram before and after the operation.

**Comment by MarcusCoding** [comment]
After the copy there were 8 GB ram free, so that shouldn't be the problem.

Could be something wrong with the config?

**Comment by SBPrime** [comment]
Actually that might be a problem. Since you have undo set to ram it will consume additional GB' when processing the operation. AWE will also consume RAM for queuing blocks. The config looks ok, although you went over the edge with: `queue-max-size-hard` :), 

This part:
```
      queue:
        #maximum size of the player block queue
        limit-hard: -1
        #number of blocks on the player queue when to stop placing blocks
        limit-soft: -1
```
You should never set those 2 to -1, if you do so it will fall back to default (10k and 75ms). If you set it to -1, -1 it would be like if you are running without AWE and the server would time out.

For OP changes where you are preparing a map and don't need to undo the operation you can always disable undo (either by using a command or in config).

In addition for long running operations I suggest changing this: `cleanOnLogout: true`

**Comment by SBPrime** [comment]
@MarcusCoding any update?

**Comment by MarcusCoding** [comment]
@SBPrime 
I think it can be closed.
Thanks for your help.
