### ISSUE TITLE
Replacing Blocks but Skips specific blocks?

### ISSUE THREAD

**Issue by copyandexecute** [SBPrime/AsyncWorldEdit#372]
Hi,

is there a way to set an area of for instance dirt but only the blocks who are not dirt will be replaced hence the calculation/replacement doesn't take as long?

**Comment by r0yzer** [comment]
hahah same problem

**Comment by SBPrime** [comment]
Such functionality is already backed in AWE and WE, before a block is queued there is a check if the target block is the same.

Actually for speed it way better to not check the block and simply place it in the chunk. Since the introduction of the new chunk system back in 1.13(?) the block get operations slowed down 100x times.
